version: '3.8'

services:
  user_db:
    image: postgres:latest
    container_name: postgres-user
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lokal
      POSTGRES_DB: warehouse_user_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  product_db:
    image: postgres:latest
    container_name: postgres-product
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lokal
      POSTGRES_DB: warehouse_product_db
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - postgres_product_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  transaction_db:
    image: postgres:latest
    container_name: postgres-transaction
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lokal
      POSTGRES_DB: warehouse_transaction_db
    restart: unless-stopped
    ports:
      - "5434:5432"
    volumes:
      - postgres_transaction_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  merchant_db:
    image: postgres:latest
    container_name: postgres-merchant
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lokal
      POSTGRES_DB: warehouse_merchant_db
    restart: unless-stopped
    ports:
      - "5435:5432"
    volumes:
      - postgres_merchant_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  notification_db:
    image: postgres:latest
    container_name: postgres-notification
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lokal
      POSTGRES_DB: warehouse_notification_db
    restart: unless-stopped
    ports:
      - "5436:5432"
    volumes:
      - postgres_notification_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  warehouse_db:
    image: postgres:latest
    container_name: postgres-warehouse
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lokal
      POSTGRES_DB: warehouse_warehouse_db
    restart: unless-stopped
    ports:
      - "5437:5432"
    volumes:
      - postgres_warehouse_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: warehouse_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  rabbitmq:
    image: rabbitmq:3-management
    container_name: warehouse_rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  user-service:
    build:
        context: ./user-service
        dockerfile: Dockerfile
    env_file:
        - ./user-service/.env
    ports:
        - "8081:8081"
    depends_on:
      user_db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    env_file:
      - ./product-service/.env
    ports:
      - "8082:8082"
    depends_on:
      product_db:
          condition: service_healthy
      redis:
          condition: service_healthy
      rabbitmq:
          condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  transaction-service:
    build:
      context: ./transaction-service
      dockerfile: Dockerfile
    env_file:
      - ./transaction-service/.env
    ports:
      - "8085:8085"
    depends_on:
      transaction_db:
          condition: service_healthy
      redis:
          condition: service_healthy
      rabbitmq:
          condition: service_healthy
      product-service:
          condition: service_started
      user-service:
          condition: service_started
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  warehouse-service:
    build:
      context: ./warehouse-service
      dockerfile: Dockerfile
    env_file:
      - ./warehouse-service/.env
    ports:
      - "8083:8083"
    depends_on:
      warehouse_db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      product-service:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  merchant-service:
    build:
      context: ./merchant-service
      dockerfile: Dockerfile
    env_file:
      - ./merchant-service/.env
    ports:
      - "8084:8084"
    depends_on:
      merchant_db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      warehouse-service:
        condition: service_started
      product-service:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    env_file:
      - ./notification-service/.env
    ports:
      - "8086:8086"
    depends_on:
      notification_db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: warehouse_api_gateway
    env_file:
      - ./api-gateway/.env
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
      user-service:
        condition: service_started
      product-service:
        condition: service_started
      merchant-service:
        condition: service_started
      notification-service:
        condition: service_started
      transaction-service:
        condition: service_started
      warehouse-service:
        condition: service_started
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  postgres_user_data:
  postgres_product_data:
  postgres_transaction_data:
  postgres_merchant_data:
  postgres_notification_data:
  postgres_warehouse_data: